### ISSUE TITLE
Crash in mainloop

### ISSUE THREAD

**Issue by benzea** [PipeWire/pipewire#110]
Hi,

I ran into a weird crash in the mainloop, I see the following three threads that may be relevant in the backtrace (I do have a coredump and can grab more information):

I believe this happened some time while creating/pre-rolling/starting a pipeline with a pipewiresrc.

The crashing line is in `loop_iterate` loop.c:343, which reads:
 ```
	spa_loop_control_hook_after(&impl->hooks_list);
```

```
Thread 14 (Thread 0x7fffc5ffb700 (LWP 22174)):
#0  0x00007ffff6984987 in epoll_wait () from /lib64/libc.so.6
#1  0x00007fffd5ce7132 in loop_iterate (ctrl=0x7fffc8013288, timeout=-1) at ../../../../Projects/jhbuild/checkout/pipewire/spa/plugins/support/loop.c:340
#2  0x00007fffd5b53216 in do_loop (user_data=0x7fffc800fbb0) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/thread-loop.c:165
#3  0x00007ffff65e358e in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff6984653 in clone () from /lib64/libc.so.6

Thread 11 (Thread 0x7fffc67fc700 (LWP 22169)):
#0  0x00007ffff65e977c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fffd5b5368e in pw_thread_loop_wait (loop=0x7fffc800fbb0) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/thread-loop.c:272
#2  0x00007fffd5d058e9 in gst_pipewire_src_create (psrc=0x7fffc800ddf0, buffer=0x7fffc67fb740) at ../../../../Projects/jhbuild/checkout/pipewire/src/gst/gstpipewiresrc.c:862
#3  0x00007ffff4054e10 in gst_push_src_create (bsrc=0x7fffc800ddf0, offset=18446744073709551615, length=4096, ret=0x7fffc67fb740)
    at ../../../../Projects/jhbuild/checkout/gstreamer/libs/gst/base/gstpushsrc.c:131
#4  0x00007ffff4037898 in gst_base_src_get_range (src=0x7fffc800ddf0, offset=18446744073709551615, length=4096, buf=0x7fffc67fb7e8)
    at ../../../../Projects/jhbuild/checkout/gstreamer/libs/gst/base/gstbasesrc.c:2512
#5  0x00007ffff4038b46 in gst_base_src_loop (pad=0x7fffc8010060) at ../../../../Projects/jhbuild/checkout/gstreamer/libs/gst/base/gstbasesrc.c:2836
#6  0x00007ffff6bf34e1 in gst_task_func (task=0x7fffdc04ba70) at ../../../../Projects/jhbuild/checkout/gstreamer/gst/gsttask.c:332
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x00007ffff6bf46bc in default_func (tdata=0xa239c0, pool=0x465110) at ../../../../Projects/jhbuild/checkout/gstreamer/gst/gsttaskpool.c:69
#8  0x00007ffff76d7e3c in g_thread_pool_thread_proxy (data=0x468740) at /home/benjamin/Projects/jhbuild/checkout/glib/glib/gthreadpool.c:307
#9  0x00007ffff76d7862 in g_thread_proxy (data=0x7fffcc002230) at /home/benjamin/Projects/jhbuild/checkout/glib/glib/gthread.c:784
#10 0x00007ffff65e358e in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffff6984653 in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fffe4e54700 (LWP 22163)):
#0  0x00007fffc80d65b0 in ?? ()
#1  0x00007fffd5ce7204 in loop_iterate (ctrl=0x7fffc801b3f8, timeout=-1) at ../../../../Projects/jhbuild/checkout/pipewire/spa/plugins/support/loop.c:343
#2  0x00007fffd5b306d7 in do_loop (user_data=0x7fffc800ef50) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/data-loop.c:37
#3  0x00007ffff65e358e in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff6984653 in clone () from /lib64/libc.so.6
```

**Comment by benzea** [comment]
```
(gdb) print impl->hooks_list
$2 = {list = {next = 0x7fffd6ffd5b0, prev = 0x7fffc801b4c0}}
(gdb) print impl->hooks_list.list->next
$3 = (struct spa_list *) 0x7fffd6ffd5b0
(gdb) print impl->hooks_list.list->next->next
$4 = (struct spa_list *) 0x7fffe4e53710
(gdb) print impl->hooks_list.list->next->next->next
$5 = (struct spa_list *) 0x9c0b90
(gdb) print impl->hooks_list.list->next->next->next->next
$6 = (struct spa_list *) 0x468380
(gdb) print impl->hooks_list.list->next->next->next->next->next
$7 = (struct spa_list *) 0x4681e0
(gdb) print impl->hooks_list.list->next->next->next->next->next->next
$8 = (struct spa_list *) 0x7
```

So, that seems wrong …

**Comment by benzea** [comment]
I just had something else bad happening with the same hook list:

```
(gdb) bt
#0  spa_list_remove (elem=0x7ff0aefe0710) at ../../../../Projects/jhbuild/checkout/pipewire/spa/include/spa/utils/list.h:57
#1  0x00007ff0ac05621f in loop_iterate (ctrl=0x7ff09c01b7f8, timeout=-1) at ../../../../Projects/jhbuild/checkout/pipewire/spa/plugins/support/loop.c:343
#2  0x00007ff0ac0736d7 in do_loop (user_data=0x7ff09c01b750) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/data-loop.c:37
#3  0x00007ff0c057458e in start_thread () from /lib64/libpthread.so.0
#4  0x00007ff0c09156a3 in clone () from /lib64/libc.so.6
(gdb) print elem
$7 = (struct spa_list *) 0x7ff0aefe0710
(gdb) print elem->next
$8 = (struct spa_list *) 0x7ff0aefe0710
(gdb) print elem->prev
$9 = (struct spa_list *) 0x7ff0aefe0710
```

Causing an infinite loop at this place, and the main thread waiting indefinitely for that thread to exit:

```
Thread 1 (Thread 0x7ff0bcfdd1c0 (LWP 7169)):
#0  0x00007ff0c0575acd in __pthread_timedjoin_ex () from /lib64/libpthread.so.0
#1  0x00007ff0ac073bdd in pw_data_loop_stop (loop=0x7ff09c01b750) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/data-loop.c:151
#2  0x00007ff0ac073a4f in pw_data_loop_destroy (loop=0x7ff09c01b750) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/data-loop.c:94
#3  0x00007ff0ac072667 in pw_core_destroy (core=0x7ff09c01b2f0) at ../../../../Projects/jhbuild/checkout/pipewire/src/pipewire/core.c:497
#4  0x00007ff0ac0c1681 in gst_pipewire_src_finalize (object=0x7ff09c00eea0) at ../../../../Projects/jhbuild/checkout/pipewire/src/gst/gstpipewiresrc.c:204
#5  0x00007ff0c192f4ae in g_object_unref (_object=0x7ff09c00eea0) at /home/benjamin/Projects/jhbuild/checkout/glib/gobject/gobject.c:3346
#6  0x00007ff0c0ae5046 in gst_object_unref (object=0x7ff09c00eea0) at ../../../../Projects/jhbuild/checkout/gstreamer/gst/gstobject.c:266
#7  0x00007ff0c0aed3b7 in gst_bin_remove_func (bin=0x1b78400, element=0x7ff09c00eea0) at ../../../../Projects/jhbuild/checkout/gstreamer/gst/gstbin.c:1812
#8  0x00007ff0c0aed7ca in gst_bin_remove (bin=0x1b78400, element=0x7ff09c00eea0) at ../../../../Projects/jhbuild/checkout/gstreamer/gst/gstbin.c:1874
#9  0x00007ff0c0ae9c38 in gst_bin_dispose (object=0x1b78400) at ../../../../Projects/jhbuild/checkout/gstreamer/gst/gstbin.c:530
#10 0x00007ff0c192f386 in g_object_unref (_object=0x1b78400) at /home/benjamin/Projects/jhbuild/checkout/glib/gobject/gobject.c:3309
[SNIP]
```

**Comment by wtay** [comment]
The reason is that it emits the before/after hooks from the data thread (to lock/unlock the threaded loop) and from the main thread (to unlock/lock to wait for completion)  at the same time, causing the list to be corrupted.

The fix is to use an iterator that is thread safe in this case (I cherry picked a patch for this issue from the work branch)
