### ISSUE TITLE
Installation fails (UnicodeEncodeError).

### ISSUE THREAD

**Issue by Achaean** [PipeWire/pipewire#52]
```
>./autogen.sh
The Meson build system
Version: 0.21.0
Traceback (most recent call last):
  File "/usr/bin/meson", line 184, in <module>
    app.generate()
  File "/usr/bin/meson", line 127, in generate
    mlog.log('Source dir:', mlog.bold(app.source_dir))
  File "/usr/share/meson/mlog.py", line 73, in log
    print(*arr, file=log_file, **kwargs) # Log file never gets ANSI codes.
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-25: ordinal not in range(128)
>
```
What Meson/Ninja versions are required?

**Comment by wtay** [comment]
0.36.0 at least here..
